# Panel_iframe
panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://192.168.10.101:9000/#/containers"
    icon: mdi:docker
    require_admin: true

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# stream:
# # ffmpeg:
# #   ffmpeg_bin: /usr/bin/ffmpeg
# camera:
#   - platform: mjpeg
#     name: iphone6s
#     mjpeg_url: http://192.168.10.183/live