esphome:
  name: esp32-cam

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "R3DUYY3EFpkgnBvQ0E5TAcCxwXS2P7WhfyRQzgCdClM="

ota:
  password: "3ee27c299f213a94f27d6329d7384bcb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Cam Fallback Hotspot"
    password: "RJpEbvN5fGyB"

captive_portal:

# Example configuration entry
switch:
  - platform: gpio
    pin: GPIO4
    id: relay
    name: "ESP32-CAM Flash 1sec On"
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: relay

# Example configuration entry
light:
  - platform: status_led
    name: "ESP32-CAM Flash On/OFF"
    pin: GPIO4

# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  idle_framerate: 0.5fps
  

  # Image settings
  name: ESP32-CAM
  # ...
