esphome:
  name: esp8266-tuya

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    # key: "qGBx9Cp6ze1b/5IMHL9OiGtXJbwQ8SkAZ209aq6Nm+w
    key: "DDe035Cr81Feubj3/CfrDpvmibEuIPhC2jhRFDL0/tc="

ota:
  # password: "bac117859c71666377e3eb2af59881e0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Tuya Fallback Hotspot"
    password: "q8rC9zzVWXgy"

captive_portal:
    